name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      # Ajoutez d'autres variables d'environnement GCP au besoin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

          # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false -var="db_password=votre_mot_de_passe"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform Apply      
        run: terraform apply -auto-approve -input=false -var="db_password=votre_mot_de_passe"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}




      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq


      - name: Terraform Output
        run: terraform output
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

          

          
          

