name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      # Ajoutez d'autres variables d'environnement GCP au besoin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

          # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false -var="db_password=votre_mot_de_passe"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform Apply      
        run: terraform apply -auto-approve -input=false -var="db_password=votre_mot_de_passe"          
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq


      - name: Terraform Output
        run: echo "::set-output name=ip_address::$(terraform output)"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Use IP Address
        run: |
          extracted_ip="${{ steps.extract_ip.outputs.ip_address }}"
          echo "Extracted IP Address: $extracted_ip"
          # Utilisez extracted_ip dans d'autres commandes ou scripts.


      - name: Set Environment Variable
        run: echo "MA_VARIABLE=ma_valeur" >> $GITHUB_ENV



      - name: EXP la Variable d'Environnement
        run: echo "CUSTOM_VAR=IT WORKS" >> $GITHUB_ENV       

      - name: Use la Variable d'Environnement        
        run: echo $CUSTOM_VAR # OK




      - name: Get Terraform Output First
        id: terraform_output
        run: echo "::set-output name=database_ip::$(terraform output database_ip)"      
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          

      - name: Use Output in Further Steps
        run: |
          output_value=${{ needs.terraform_output.outputs.database_ip }}
          echo "DATABASE_IP=$output_value" >> $GITHUB_ENV




        

        


      - name: Continue with Further Steps
        run: |
          output_value=${{ env.DATABASE_IP }}
          echo "Continuing with DATABASE_IP=$output_value"

          
      - name: Try
        run: |
          output=$(terraform output database_ip)
          echo $output
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}



        



          

          
          

